title:            Codice Insicuro
description:      Il blog italiano di application security croccante fuori e morbido dentro
version: 1.2
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://localhost:4000
# url:              https://codiceinsicuro.it
disqus_shortname: codiceinsicuro

# Owner/author information
owner:
  name:           Paolo Perego
  avatar:         myself.png
  bio:            "Application Security Specialist, 37enne da Milano, Italia. Padre e marito orgoglioso nonchè atleta di Taekwon-do ITF"
  email:          paolo@armoredcode.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        codiceinsicuro
  facebook:       codiceinsicuro
  github:         thesp0nge
  stackoverflow:  
  linkedin:       thesp0nge
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  feedburner: CodiceInsicuro
  # For Google Authorship https://plus.google.com/authorship
  google_plus: PaoloPerego

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-50260618-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Archivio
    url: /posts/
  - title: Codesake::Dawn
    url: http://dawn.codesake.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /blog/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: true
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
