name: Codice Insicuro
title: Codice Insicuro, blog di Cyber Security, sviluppo sicuro, code review e altro.
description: I pirati della sicurezza applicativa
meta_description: I pirati della sicurezza applicativa
author:
  name: "Paolo Perego"
  email: paolo@codiceinsicuro.it
  twitter: thesp0nge
  facebook: CodiceInsicuro
  github: thesp0nge
  uri: https://plus.google.com/+PaoloPerego
  bio: Specialista di Sicurezza Applicativa, 39enne vive a Milano, Italia. E' un marito e padre orgoglioso di Daniele e Anna. Quando non buca siti o insegna a scrivere codice sicuro, sviluppa un tool di code review per ruby (<a href="http://dawnscanner.org">dawnscanner</a>), e su twitter lo trovi seguendo <a href="https://twitter.com/thesp0nge">@thesp0nge</a>. E' anche una cintura nera 2 DAN di Taekwon-do ITF.

version: '2.4'
disqus_shortname: codiceinsicuro

permalink:   /blog/:title/
markdown: kramdown
kramdown:
  toc_levels: 1..3

highlighter: pygments
logo: sicuropoli.jpg
paginate: 15
baseurl: /
domain_name: 'https://codiceinsicuro.it'
google_analytics: 'UA-50260618-1'

buffer:
  config: buffer.yml
  share: false

include:
  - _pages
  # - _rimedi
  # - _chicchi_di_java

exclude:
  - Capfile
  - config
  - log
  - Rakefile
  - tmp
  - TODO
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - Gruntfile.js
  - package.json
  - .jekyll-assets-cache
  - .asset-cache
  - .sass-cache
  - .bundle
  - .jekyll-metadata

gems:
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-assets
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

collections:
  rimedi:
    output: true
    permalink: /:collection/:title/
    title: I rimedi veloci del bucaniere
  chicchi:
    output: true
    permalink: /:collection/:title/
    title: Il caffè del buongiorno

defaults:
  - scope:
      path: _chicchi
      type: chicchi
    values:
      layout: chicchi
      image:
        feature: java.jpg
        credit: Lilian Wong
        creditlink: https://flic.kr/p/7Ubonh

  - scope:
      path: _rimedi
      type: tip
    values:
      layout: tip

gist:
  noscript: false


# Details for the RSS feed generator
url:            'https://codiceinsicuro.it'
# url:            'http://localhost:4000'
