name: Codice Insicuro
description: I pirati della sicurezza applicativa
meta_description: I pirati della sicurezza applicativa
author: Paolo Perego
bio: Specialista di Sicurezza Applicativa, 39enne che vive a Milano, Italia. Padre e marito orgoglioso e quando non buco siti o scrivo codice sicuro, atleta ed istruttore di Taekwon-do ITF

version: '2.2'
disqus_shortname: codiceinsicuro
markdown: kramdown
highlighter: pygments
logo: sicuropoli.jpg
paginate: 15
baseurl: /
domain_name: 'https://codiceinsicuro.it'
google_analytics: 'UA-50260618-1'
permalink:   /blog/:title

buffer:
  config: buffer.yml
  share: true
# Details for the RSS feed generator
# url:            'https://codiceinsicuro.it'
url:            'http://localhost:4000'
